/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:31108f87-a613-4b5d-b264-9e45c7d09408",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_VrWNdgG4R",
    "aws_user_pools_web_client_id": "2or5qov41d9ac72t4kvc9kob7d",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "booksdb-dev",
            "region": "ap-south-1"
        }
    ],
    "aws_user_files_s3_bucket": "booktobucket175249-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_cloud_logic_custom": [
        {
            "name": "booksapi",
            "endpoint": "https://tdw4u1hpeg.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
